---
- name: Provision VMware vSphere VMs with Terraform
  hosts: localhost
  gather_facts: false
  
  roles:
    - terraform

  post_tasks:
    - name: Add provisioned VMs to inventory
      add_host:
        name: "{{ item.name }}"
        ansible_host: "{{ item.ip }}"
        ansible_user: ubuntu
        ansible_ssh_private_key_file: ~/.ssh/id_rsa
        groups: vms
      loop: "{{ vms }}"
